name: Build and Run Docker

on:
  push:
    branches:
      - master

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build Docker image
      run: docker build -t hello-world-python .

    - name: Run Docker container
      run: docker run hello-world-python